server/src/services/mail-service/MailService.class.ts
Fixes an issue where the `from` field of a mail does not get set to an email. This was due to the fact that `auth.user` does NOT have to be an email.
=> Fix 'from' in mail-service not being set correctly.

server/config/default.yml, server/src/services/mail-service/MailService.class.ts
Primarily this adds more logging to the MailService. Furthermore this introduces a `testingMode` which can be used to connect to ethereal by providing the user and pass accordingly. This replaces the auto-use of ethereal in non-production environments.
=> Add testing mode flag & more logging to MailService.

.github/workflows/code-quality.yml, package.json
This is due to the fact that this is now included as postinstall script in the root package.json.
=> Remove building shared package from workflow.

client/src/components/forms/TutorialForm.tsx, client/src/hooks/fetching/Tutorial.ts, client/src/typings/types.ts, client/src/util/helperFunctions.ts, client/src/view/attendance/AttendanceManager.tsx, client/src/view/tutorialmanagement/TutorialManagement.tsx, docker-compose.yaml, server/src/services/tutorial-service/TutorialService.class.ts, server/src/services/tutorial-service/TutorialService.routes.ts, shared/src/model/User.ts
Fixes the bug where a substitute tutor cannot load the attendance page. This introduces a new endpoint `/tutorial/:id/tutor` which only returns the name of the tutor of the tutorial. 
- Closes #53
=> Substitute tutor cannot view attendance page

client/src/hooks/fetching/Tutorial.ts, client/src/view/management/components/ExtendableStudentRow.tsx, client/src/view/studentmanagement/Studentmanagement.tsx, server/src/services/scheincriteria-service/ScheincriteriaService.class.ts, server/src/services/scheincriteria-service/ScheincriteriaService.routes.ts, server/src/services/tutorial-service/TutorialService.routes.ts
Fixes the issue of tutors not able to retrieve the schein statuses of their students. This is done by using an endpoint specially made for this purpose.
- Closes #60
=> Tutors cannot retrieve schein statuses of their students

Readme.md, client/src/components/forms/StudentForm.tsx, shared/src/validators/Student.ts
Different universities have different matriculation number length. This PR makes it possible to enter 6 (or more) digit matriculation numbers instead of the fixed length of 7. 
However this itself could only be a "hotfix" and more adjustments could be neccessary. One overall solution would be to provide a setting for the minimal length after the setting system has been added.
- Closes #52
=> Allow 6 digit matriculation numbers

client/src/hooks/LoginService.tsx
Fixes special characters not being encoded properly for the Authorization header. The axios library does not force UTF-8 for the encoding process so the encoding is done outside the library, now.
- Closes #87
=> Fix special characters not working in usernames on login.

client/src/components/TableWithForm.tsx, client/src/view/App.tsx
Fixes an issue with the height of the main page in Firefox. The previous CSS style lead to cut off pages at the bottom in said browser.
- Closes #77
=> Fix page being cut off at the bottom in Firefox.

client/src/components/CustomSelect.tsx, client/src/components/forms/TutorialForm.tsx, client/src/hooks/fetching/User.ts, client/src/view/tutorialmanagement/TutorialManagement.tsx, client/src/view/tutorialmanagement/TutorialSubstituteManagement.tsx, server/src/services/tutorial-service/TutorialService.class.ts, shared/src/model/Tutorial.ts, shared/src/validators/Tutorial.ts
Adds the ability to remove a substitute tutor after he/she was assigned as a substitute. This also includes some changes to more basic components:
- `CustomSelect` can handle a 'none item' which can be used to deselect a selection made.
- `getUsers` returns the users sorted ascending by their names ('lastname, firstname').
- Closes #97 
- Closes #41
=> Make substitute tutors removable after setting them

client/src/components/forms/components/SubmitButton.tsx, client/src/hooks/fetching/Tutorial.ts, client/src/hooks/fetching/User.ts, client/src/util/helperFunctions.ts, client/src/view/attendance/AttendanceManager.tsx, client/src/view/pointsmanagement/ScheinExamPointEntry.tsx, client/src/view/pointsmanagement/components/EditStudentPointsDialogContent.tsx, client/src/view/studentmanagement/Studentmanagement.tsx, client/src/view/tutorialmanagement/TutorialManagement.tsx, client/src/view/tutorialmanagement/TutorialSubstituteManagement.tsx, client/src/view/usermanagement/UserManagement.tsx, server/src/services/pdf-service/PdfService.class.ts, shared/src/util/helpers.ts
Adds a button to the attendance page with which one can set all students to `PRESENT` if they don't have an `AttendanceState` already.
This PR also fixes / changes some small things:
- Fix attendance PDF not being sorted by name.
- Move `getNameOfEntity` function to the shared/ package.
- Sort students after fetching them in tutorial.
- Closes #76
=> Add ability to set all students to present at once for one day

client/src/components/forms/StudentForm.tsx, client/src/hooks/fetching/Student.ts, client/src/view/studentmanagement/AllStudentsAdminView.tsx, client/src/view/studentmanagement/Studentmanagement.tsx, docker-compose.yaml, server/src/model/documents/StudentDocument.ts, server/src/server.ts, server/src/services/student-service/StudentService.class.ts, server/src/services/team-service/TeamService.class.ts, tsconfig.json
Adds the ability to the server to recover from an inconsistent state regarding students and their teams: If a student is assigned to a team that does not exist the server will remove that team and return the student without it.
This also adds a catch to the fetching function for the team of a student in the client to prevent full crashes if a team could not be found.
=> Fix for inconsistent student-team state

Dockerfile, client/src/components/forms/TutorialForm.tsx, client/src/util/axiosTransforms.ts, client/src/view/attendance/AttendanceManager.tsx, client/src/view/dashboard/components/TutorialStatsCard.tsx, client/src/view/pointsmanagement/ScheinExamManagement.tsx, client/src/view/studentmanagement/AllStudentsAdminView.tsx, client/src/view/studentmanagement/Studentmanagement.tsx, client/src/view/tutorialmanagement/TutorialSubstituteManagement.tsx, package.json, server/package.json, server/src/model/documents/TutorialDocument.ts, server/src/model/dtos/LoggedInUserDTO.ts, server/src/services/tutorial-service/TutorialService.class.ts, shared/src/model/Tutorial.ts, yarn.lock
Fixes issues in the code regarding substitutes not having access to the dates of the tutorial.
This also updates puppeteer to 1.19.0 due to the fact that the alpine package of chromium got updated to version 77 aswell. 
- Closes #137
=> Fixes no dates in substitute attendance dropdown available

client/src/components/drawer/Drawer.tsx, client/src/hooks/FetchingService.ts, client/src/hooks/fetching/Information.ts, client/src/view/AppBar.tsx, server/src/app.ts, server/src/server.ts, server/src/services/information-service/InformationServcive.routes.ts, server/src/services/information-service/InformationService.class.ts, server/src/services/scheincriteria-service/ScheincriteriaService.routes.ts
Add a version indicator to both the server and the client.
Additionally this changes the order of operations on the server start: Now a connection to the DB is established before anything else. Afterwards the schein criteria blueprints get loaded before the rest of the startup routine is executed.
- Closes #135
=> Add version indicator to server log and client page

server/src/services/student-service/StudentService.class.ts
Fixes an issue where a student could not be moved to a different tutorial due to the wrong (out-dated) document being used.
=> Fix changing tutorial of student not working.

server/src/services/pdf-service/PdfService.class.ts, server/src/services/team-service/TeamService.class.ts
This PR adds tables to the generated assessment PDFs to display the achieved points in the subexercises. The tables will only be visible if the exercise contains subexercises.
- Closes #182
=> Add achieved points of subexercises to the generated PDFs.

client/src/components/forms/components/FormikMarkdownTextfield.tsx, client/src/components/forms/components/FormikTextField.tsx
If the FormikMarkdownTextField gains focus it does NOT select all it's text anymore. This makes it easier to fix typos in the assessment comments.
This changes FormikTextField aswell to support disabling the behaviour which selects all text in the TextField if it gets the focus.
- Clsoes #186
=> Disable the "select all" behaviour on the markdown field if it gains focus.

server/src/services/scheinexam-service/ScheinexamService.class.ts, server/src/services/sheet-service/SheetService.class.ts
This fixes an issue with the calculation of the total points of a sheet / scheinexam. The bonus points of subexercises where added as if they are "regular" points.
=> Fix bonus points getting added to total points on evaluation.

server/package.json
After updating to TypeScript 3.7 the output structure of the server build changed and does not contain the config folder anymore. This is fixed with this PR.
=> Fix config folder being copied to the wrong folder.

client/package.json, client/src/view/AppBar.tsx, client/src/view/dashboard/Dashboard.tsx, client/src/view/dashboard/components/TutorialStatistics.tsx, server/src/services/excel-service/ExcelService.routes.ts
This moves the download buttons for the tutorial backups to the AppBar and removes them from the Dashboard. This way an ever-loading dashboard does not prevent the user from downloading the backup.
Furthermore this PR allows correctors to download the backups aswell.
- Closes #193
=> Change the position of the backup download button

server/src/services/tutorial-service/TutorialService.class.ts
This adds sorting of dates before the tutorial gets send as a response by the API.
- Closes #218
=> Fix dates of tutorials not getting sorted.

.github/RELEASE_TEMPLATE.md, client/package.json, client/src/components/forms/UserForm.tsx, client/src/view/studentmanagement/AllStudentsAdminView.tsx, dev-tools/src/fetch/helpers.ts, dev-tools/src/generateStudents.ts, package.json, server/src/model/documents/StudentDocument.ts, server/src/model/documents/TeamDocument.ts, server/src/model/scheincriteria/Scheincriteria.ts, server/src/model/scheincriteria/criterias/AttendanceCriteria.ts, server/src/model/scheincriteria/criterias/PresentationCriteria.ts, server/src/model/scheincriteria/criterias/ScheinexamCriteria.ts, server/src/model/scheincriteria/criterias/SheetIndividualCriteria.ts, server/src/model/scheincriteria/criterias/SheetTotalCriteria.ts, server/src/services/pdf-service/modules/PDFModule.ts, server/src/services/pdf-service/modules/PDFWithStudentsModule.ts, server/src/services/pdf-service/modules/ScheinResultsPDFModule.ts, server/src/services/pdf-service/modules/ScheinexamResultPDFModule.ts, server/src/services/scheincriteria-service/ScheincriteriaService.class.ts, server/src/services/sheet-service/SheetService.class.ts, server/src/services/student-service/StudentService.class.ts, yarn.lock
This PR solves the issue that the calculation of the schein statuses of all students slow down the TMS afterwards. It is achieved by streamlining the calculation process and greatly reducing the amount of needed asynchronous tasks (like fetching information from the DB).
- Closes #234 
- Closes #232
=> Calculation of all schein statuses of all students lead to slow tms afterwards

client/src/components/SplitButton.tsx, client/src/hooks/fetching/Files.ts, client/src/hooks/fetching/Tutorial.ts, client/src/typings/types.ts, client/src/view/dashboard/Dashboard.tsx, client/src/view/studentmanagement/AllStudentsAdminView.tsx, client/src/view/studentmanagement/student-overview/Studentoverview.tsx, client/src/view/studentmanagement/student-overview/components/StudentRow.tsx, client/src/view/studentmanagement/student-store/StudentStore.reducers.ts, client/src/view/studentmanagement/student-store/StudentStore.tsx, package.json, server/src/services/pdf-service/PdfService.class.ts, server/src/services/pdf-service/PdfService.routes.ts, server/src/services/pdf-service/modules/ScheinResultsPDFModule.ts
This PR adds the following things:
- Add option for admin to generate a schein status overview list without the matriculation numbers getting shortened.
- Re-add the "passed / not passed" labels to the student overview after #235 fixed the slow status calculations.
=> Add small adjustments

client/src/hooks/LoginService.helpers.ts, client/src/hooks/LoginService.tsx, client/src/model/LoggedInUser.ts, client/src/model/Student.ts, client/src/pages/AppBar.tsx, client/src/pages/dashboard/Dashboard.tsx, client/src/pages/studentmanagement/student-list/components/TutorialChangeForm.tsx, server/src/database/models/student.model.ts, server/src/database/models/tutorial.model.ts, server/src/database/models/user.model.ts, server/src/module/user/user.service.ts, server/src/shared/model/Common.ts, server/src/shared/model/Student.ts, server/src/shared/model/User.ts
This fixes that the tutorials got sorted on the client side only by slot. Tutorials now get sorted by `weekday?  first, by `startTime` second and by `slot` last.
- Closes #705
=> Fix wrong sorting of tutorials

client/src/components/TeamTableRow.tsx, client/src/components/forms/StudentForm.tsx, client/src/components/forms/TeamForm.tsx, client/src/hooks/fetching/Team.ts, client/src/model/Student.ts, client/src/model/Team.ts, client/src/pages/attendance/components/StudentsAttendanceRow.tsx, client/src/pages/import-short-tests/components/map-students-ilias-names/MapStudentsToIliasNames.tsx, client/src/pages/import-short-tests/components/map-students-ilias-names/MappingDialog.tsx, client/src/pages/points-scheinexam/overview/components/StudentCard.tsx, client/src/pages/points-sheet/enter-form/EnterStudentPoints.tsx, client/src/pages/points-sheet/overview/components/TeamCard.tsx, client/src/pages/student-info/StudentInfo.tsx, client/src/pages/studentmanagement/student-list/StudentList.helpers.ts, client/src/pages/teamoverview/Teamoverview.tsx, server/src/database/models/student.model.ts, server/src/database/models/team.model.ts, server/src/shared/model/Team.ts
This fixes the issue described in #706.
Furthermore this PR removes the `tutorial` attribute from the students in a teams response because the information is already present in the "wrapping" team. More information can be found in the related commit 1631d489505cdb94b2ddce894ddb6df6f2f1c2d9.
- Closes #706
=> Fix team during student creation always stays at create new team

.github/RELEASE_TEMPLATE.md, package.json
The `github-markdown-css` package was listed as a devDependency and therefore was not installed properly in the production image.
=> Fix github-markdown-css being a devDependency.

client/src/pages/App.tsx, client/src/pages/studentmanagement/student-list/StudentList.tsx
Safari did fail on interpreting some of the box CSS. If the height was set on the `content` box the height of sub components was not properly set/updated for child components.
- Closes #792
=> [Safari] Fix student overview not showing the student list

build-docker-image.ts, client/src/model/Team.ts
The team's `getGrading()` function did not return a grading properly if the team only has one student.
- Closes #806
=> Fix TeamCards not showing grading if team has only one student.

client/public/index.pug, client/src/components/forms/components/FormikMarkdownTextfield.tsx
Changes the font of the markdown input textfield to a monospaced font for better readability (especially for code parts).
- Closes #862
=> Change font of markdown textfield to Roboto Mono (monospaced font).

client/src/hooks/fetching/Student.ts
The request on setting the gradings of multiple students (ie importing short test results) could timeout in some occasions. However, the server is correctly processing the request - it just takes a little longer - so it must not timeout.
=> Fix timout on setting gradings of multiple students.

server/src/module/scheincriteria/container/criterias/ShortTestCriteria.ts
Fixes that the short test calculation does not use the percentage set in the test.
=> Fix passed state of shorttest not being calculation correctly.

client/snowpack.config.js, client/src/components/markdown/Markdown.tsx, client/src/hooks/useFetchState.ts, client/src/hooks/useSettings.tsx, client/src/pages/AppBar.tsx, client/src/pages/dashboard/Dashboard.tsx, client/src/pages/hand-ins/short-test-management/ShortTestManagement.tsx, client/src/pages/import-short-tests/components/adjust-generated-short-test/AdjustGeneratedShortTest.tsx, client/src/pages/import-short-tests/components/map-students-ilias-names/IliasMapping.context.tsx, client/src/pages/import-users/adjust-data-form/AdjustImportedUserDataForm.tsx, client/src/pages/student-info/StudentInfo.tsx, client/src/pages/studentmanagement/student-list/StudentList.helpers.ts, client/src/pages/studentmanagement/student-list/components/TutorialChangeForm.tsx, client/src/pages/tutorial-substitutes/SubstituteManagement.context.tsx, client/src/pages/tutorialmanagement/TutorialManagement.context.tsx, client/src/pages/tutorialmanagement/TutorialManagement.tsx, client/src/pages/tutorialmanagement/sorters/Sorters.ts, client/src/pages/usermanagement/UserManagement.tsx, server/src/shared/model/Tutorial.ts
Add sorting options to the tutorials management page.
- Closes #870
=> Fix tutorials not being sorted by date on the tutorial management page.

server/src/module/scheincriteria/container/criterias/ShortTestCriteria.ts
This is a hotfix and should be better solved by resolving #949. Please note that for this hotfix the "percentagePerTest" attribute is ignored inside the ShortTestCriteria.
=> Fix wrong calculation of short test passed state.

client/src/components/UploadFileButton.tsx, client/src/components/import-csv/components/ImportCSVFromFile.tsx
Fixes the bug that the csv import loads forever.
- replaces hardcoded .csv in `accept` with the content types
- remove check for content type afterwards as it is now already checked by the upload itself (therefore it can never be an invalid content type), and if the validation fails it would only cause the bug of an infinite load
- changes the content type for the csv import to `text/csv`, as `application/vnd.ms-excel` [seems to be .xls and not .csv](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
- Fixes #1011
=> fix csv upload: accept correct content type

client/src/model/Grading.ts, server/src/database/entities/grading.entity.ts, server/src/module/markdown/markdown.service.ts
Fixes grading point bugs with exercises with subexercises
- adds totalPoints to entity
- use in points of property of entity to fulfill contract
- use new totalPoints in pdf generation
- fix frontend Grading entity to use totalPoints
- Closes #1023
=> fix grading of exercises with subexercises

client/src/components/PointsTextField.tsx, client/src/components/forms/StudentForm.tsx
It is now impossible to assign more points for an exercise than allowed
The problem was that max attribute takes a number and it was provided a ExercisePointsInfo object
The iliasname of a student must be unique now in case it is specified
#1025 and #968
=> Fix sanity check for assigning more grading points than achievable and add uniqueness constraint for Ilias Names

client/src/components/forms/TutorialForm.tsx, client/src/components/forms/components/FormikTutorialSelect.tsx, client/src/hooks/dialog-service/DialogService.tsx, client/src/model/Student.ts, client/src/model/Tutorial.ts, client/src/pages/student-info/components/AttendanceInformation.tsx, client/src/pages/tutorial-substitutes/components/SelectSubstitute.tsx, client/src/pages/tutorialmanagement/TutorialManagement.tsx, client/src/pages/tutorialmanagement/components/TutorialTableRow.tsx, scripts/build-test-docker/config/templates/attendance.pug, server/config/templates/attendance.pug, server/src/database/entities/tutorial.entity.ts, server/src/database/entities/user.entity.ts, server/src/guards/created-in-own-tutorial.guard.ts, server/src/guards/tutorial.guard.ts, server/src/module/pdf/subservices/PDFGenerator.attendance.ts, server/src/module/scheincriteria/container/criterias/AttendanceCriteria.ts, server/src/module/template/template.types.ts, server/src/module/tutorial/tutorial.dto.ts, server/src/module/tutorial/tutorial.service.spec.ts, server/src/module/tutorial/tutorial.service.ts, server/src/module/user/user.service.spec.ts, server/src/shared/model/Tutorial.ts, server/src/shared/util/helpers.ts, server/test/mocks/entities.mock.ts
Adds a new feature that allows several users to have the TUTOR role in a tutorium
Fix label overflow in dialog windows
Fix student attendance info tab and chart
#791 #161 #1015
=> Feature several tutors in a tutorium

client/src/components/forms/TutorialForm.tsx, client/src/components/forms/UserForm.tsx
Ensure that a person who is both a tutor and a corrector cannot be assigned the tutor and the corrector to the same tutorium
#1021
=> Bugfix disallow tutor and corrector in the same tutorium

client/src/pages/points-sheet/enter-form/EnterTeamPoints.tsx
When entering team points and saving them, then switching to another team using team select button and back to the previous team, the old values of the team were displayed. This pull request fixes this bug
=> Fix entered team points when switching teams using select button
