TMS-Uni-Stuttgart/Tutor-Management-System

client/src/components/forms/SheetForm.tsx
client/src/components/forms/components/FormikMarkdownTextfield.tsx
client/src/hooks/FetchingService.ts
client/src/hooks/fetching/Files.ts
client/src/view/dashboard/Dashboard.tsx
client/src/view/dashboard/components/TutorialStatistics.tsx
server/package.json
server/src/model/Errors.ts
server/src/model/documents/StudentDocument.ts
server/src/server.ts
server/src/services/excel-service/ExcelService.class.ts
server/src/services/excel-service/ExcelService.routes.ts
server/src/services/student-service/StudentService.class.ts
server/src/services/user-service/authentication.routes.ts
server/src/typings/excel4node.d.ts
yarn.lock

Adds support to the server to export XLSX files aswell as some UI to the client to allow it.
- Closes #42

Add support of exporting XLSX files.

---

client/src/components/PaperTableRow.tsx
client/src/components/forms/StudentForm.tsx
client/src/components/forms/components/FormikTextField.tsx
client/src/components/forms/components/FormikTextFieldWithButtons.tsx
client/src/util/RoutingPath.tsx
client/src/util/styles.ts
client/src/view/management/components/ExtendableStudentRow.tsx
client/src/view/studentmanagement/AllStudentsAdminView.tsx
client/src/view/studentmanagement/Studentmanagement.tsx
server/src/model/documents/StudentDocument.ts
server/src/services/pdf-service/PdfService.class.ts
server/src/services/student-service/StudentService.class.ts
shared/src/model/Student.ts
shared/src/validators/Student.ts

This allows the tutor to enter student data and **opt-out** of the matriculation number being required if necessary (ie student did not provide one).
- Closes #51

Allow not entering a matriculation number

---

client/src/components/forms/UserForm.tsx
client/src/components/forms/components/FormikExerciseEditor.tsx
client/src/hooks/fetching/Axios.tsx
client/src/view/management/components/ExtendableTeamRow.tsx
client/src/view/usermanagement/UserManagement.tsx
server/src/services/user-service/UserService.class.ts
shared/src/model/User.ts
shared/src/validators/Tutorial.ts
shared/src/validators/User.ts

Implements the ability for the administrator to change the username of the users if neccesary. This also checks (client & server side) if an username is already taken before creating / changing the user.
- Closes #93

Allow changing the username of users

---

client/src/components/forms/StudentForm.tsx
client/src/view/studentmanagement/Studentmanagement.tsx
server/src/services/student-service/StudentService.class.ts

The `StudentForm` auto-fills teams on student creation until they have a certain member count. For more information see #103.
- Closes #103

Automatically assign student to a team on creation

---

client/src/hooks/fetching/Student.ts
client/src/view/attendance/AttendanceManager.tsx
client/src/view/attendance/components/CakeCount.tsx
client/src/view/attendance/components/StudentsAttendanceRow.tsx
server/src/model/documents/StudentDocument.ts
server/src/services/student-service/StudentService.class.ts
server/src/services/student-service/StudentService.routes.ts
shared/src/model/Student.ts
shared/src/validators/Student.ts

Adds a system to track which student has to bring how many cakes due to - for example - being too late.
- Closes #75

Add cake tracking system

---

client/src/view/studentmanagement/AllStudentsAdminView.tsx
client/src/view/studentmanagement/Studentmanagement.tsx

Fix student pages not loading if student is in a non-existing team by adding an error handler.
- Closes #111

Fix student page not loading on missing team

---

.github/workflows/code-quality.yml
build-docker-image.ts
server/src/model/documents/TeamDocument.ts
server/src/services/pdf-service/PdfService.class.ts
server/src/services/team-service/TeamService.class.ts

Fixes an issue with saving the teams after removing a student. Mongoose now gets notified that the tutorial's team array has changed.
This also comes with auto-repair code that if a team contains a student which does not exist this student gets removed.
- Closes #131

Fix removing a student from a team not saved properly.

---

build-docker-image.ts

Update docker build script to use docker repo name.

---

client/src/components/forms/ChangePasswordForm.tsx
package.json
server/src/model/documents/TutorialDocument.ts
server/src/services/pdf-service/PdfService.class.ts
server/src/services/student-service/StudentService.class.ts

Fixes the issue with the passwords by not allow `:` as a character in the password.
The generation of the attendance sheet also got fixed by removing all students from the tutorial which could not be fetched.
- Closes #112 
- Closes #129

Fixes passwords & attendance sheet generation

---

.vscode/typescriptreact.code-snippets
client/package.json
client/src/components/Markdown.tsx
client/src/components/forms/components/FormikMarkdownTextfield.tsx
client/src/view/pointsmanagement/PointManagement.tsx
package.json
server/package.json
server/src/services/pdf-service/PdfService.class.ts
server/src/services/pdf-service/PdfService.utils.ts
yarn.lock

This fixes the server producing new lines if the text contains new lines. Furthermore this enables the use of emojis with their unicode characters. ~~with the `:smile:` syntax from GitHub~~ 
- Closes #166

Fix serverside markdown removing additional lines.

---

client/src/view/pointsmanagement/PointManagement.tsx
client/src/view/pointsmanagement/components/points-card/ExerciseBox.tsx
client/src/view/pointsmanagement/components/points-card/PointsCard.tsx
client/src/view/pointsmanagement/components/points-card/PointsTextField.tsx
client/src/view/usermanagement/UserManagement.tsx
server/src/model/documents/ExerciseDocument.ts
server/src/server.ts
server/src/services/pdf-service/PdfService.class.ts
server/src/services/team-service/TeamService.class.ts
server/tsconfig.json
shared/src/model/Points.ts

This PR aims at closing some issues which are all related to the correction UI and/or the underlying systems.

Fix bonus points not being distinct & file extension missing in some cases in some browsers.

---

client/src/components/TeamTableRow.tsx
client/src/view/pointsmanagement/PointManagement.tsx
client/src/view/teamoverview/Teamoverview.tsx
server/package.json
server/src/services/student-service/StudentService.class.ts
server/src/services/team-service/TeamService.class.ts
server/test/teams.test.ts
server/test/users.test.ts
server/test/util/Test.Assertions.ts
yarn.lock

This PR closes several issues. All of them are team related and therefore get bundled.

Fix teams not getting updated properly

---

Dockerfile
package.json
server/package.json
server/src/services/excel-service/ExcelService.class.ts
yarn.lock

Adds a hotfix for the attendances in the generated XLSX file. For now, the resulting timezone is fixed. This is due to the fact that all date-related systems need an overhaul, however, that might break compatability with previous versions. Therefore the overhaul will be done in a future version (probably version 2).
- Closes #128

Add hotfix for wrong dates used in XLSX file for attendances.

---

client/src/components/Markdown.tsx

This fixes the preview dialog in the PointManagement having the wrong background.

Fix background of markdown preview being black.

---

.vscode/launch.json
client/src/hooks/fetching/Axios.tsx
dev-tools/package.json
dev-tools/src/generateStudents.ts
dev-tools/tsconfig.json
package.json
server/config/default.yml
server/src/services/scheincriteria-service/ScheincriteriaService.class.ts

If there are many students (ie `> 600`) the dashboard and the studentoverview time out if an admin try to load them. This is due to the results of the schein criterias take too long to load.

Fix timeout on dashboard / studentoverview for admins

---

server/config/default.yml
server/src/model/documents/StudentDocument.ts
server/src/services/student-service/StudentService.class.ts

Fix student not being removed from team.

---

server/src/model/Errors.ts
server/src/server.ts
server/src/services/pdf-service/PdfService.class.ts

Add routine at start which checks if all template files could be found.

---

server/src/services/student-service/StudentService.class.ts

This was due to the `points` property in the `StudentDocument` not getting properly set as modified.
- Closes #209

Fix points in students not being properly saved.

---

server/src/app.ts
server/src/helpers/config.ts

Adds more logging to the server. The goal is to have better logs to better identify issues in erroneous scenarios.

Enhance logging on the server

---

client/src/components/forms/StudentForm.tsx
client/src/view/points-scheinexam/enter-form/EnterScheinexamPoints.tsx
client/src/view/points-sheet/overview/components/TeamCard.tsx
client/src/view/studentmanagement/TutorStudentmanagement.tsx
client/src/view/studentmanagement/student-overview/Studentoverview.helpers.ts
client/src/view/tutorialmanagement/TutorialManagement.tsx
client/src/view/tutorialmanagement/TutorialSubstituteManagement.tsx
server/src/services/pdf-service/modules/AttendancePDFModule.ts
server/src/services/pdf-service/modules/CredentialsPDFModule.ts
shared/src/util/helpers.ts

This fixes the issue with names being displayed like "Harry Potter" even though they should be displayed as "Potter, Harry".
- Closes #223

Fix names being displayed "firstname lastname" instead of "lastname, firstname"

---

.github/RELEASE_TEMPLATE.md
client/src/components/info-paper/InfoPaper.tsx
client/src/components/points-table/PointsTable.tsx
client/src/view/studentmanagement/student-info/StudentInfo.tsx
client/src/view/studentmanagement/student-info/components/CriteriaCharts.tsx
client/src/view/studentmanagement/student-info/components/ScheinExamInformation.tsx
client/src/view/studentmanagement/student-info/components/StudentDetails.tsx

This PR adds the evaluations of the scheinexams to the student information aswell as the general information of a student.
- Closes #226

Add more information to the student information page.

---

server/package.json
yarn.lock

Update NestJS packages.

---

.github/workflows/docker-build-test.yml
dev-tools/build-test-docker/buildAndTestDocker.ts

Add an action which checks if the docker image can be build. Furthermore the following things are tested with the build image:
- Properly configured container would start using the image.
- Started server can serve a PDF (ie puppeteer is working properly).

Add workflow for testing the docker image.

---

.eslintrc.yml
client/src/components/CustomSelect.tsx
client/src/components/generatedForm/components/GeneratedField.tsx
client/src/components/generatedForm/generateInitialValues.ts
client/src/hooks/DialogService.tsx
client/src/serviceWorker.ts
client/src/util/Logger.ts
client/src/view/attendance/AttendanceManager.tsx
client/src/view/scheincriteriamanagement/ScheinCriteriaManagement.tsx
client/src/view/scheinexam-management/ScheinExamManagement.tsx
client/src/view/sheetmanagement/SheetManagement.tsx
client/src/view/studentmanagement/student-overview/Studentoverview.helpers.ts
client/src/view/teamoverview/Teamoverview.tsx
client/src/view/tutorialmanagement/TutorialManagement.tsx
dev-tools/build-test-docker/buildAndTestDocker.ts

This adds a logger to the client which replaces `console.log` calls throughout the application.
- #363

Add logger to the client

---

client/src/pages/studentmanagement/AllStudentsAdminView.tsx
client/src/pages/studentmanagement/TutorStudentmanagement.tsx
client/src/pages/studentmanagement/student-overview-new/StudentList.helpers.ts
client/src/pages/studentmanagement/student-overview-new/StudentList.tsx
client/src/pages/studentmanagement/student-overview-new/components/StudentListRow.tsx
server/src/database/models/user.model.ts
server/src/module/scheincriteria/scheincriteria.service.ts
server/src/shared/model/ScheinCriteria.ts

This decreases the wait time for the student's summaries a bit by including each student with the summary information.

Speed up student summary retrieval

---

client/src/components/PaperTableRow.tsx
client/src/pages/usermanagement/components/UserTableRow.tsx

Adds the display of the username of a user to the list of users.
- Closes #37

Add username to UserTableRow.

---

CONTRIBUTING.md
Readme.md
client/src/components/forms/components/FilterableSelect.tsx
server/config/development.yml
server/src/database/models/grading.model.ts
server/src/database/models/models.module.ts
server/src/database/models/student.model.ts
server/src/database/models/team.model.ts
server/src/module/markdown/markdown.service.ts
server/src/module/student/grading.service.ts
server/src/module/student/student.service.spec.ts
server/typings/mongoose-field-encryption.d.ts

This is an attempt to fasten the fetch of students from the DB because creating mongoose documents is considered to be slow. Maybe using "normal" objects and the class-transformer package is a faster alternative.
This is one possible part of the solution for #627

Change Gradings in students to be objects (instead of mongoose docs).

---

.github/workflows/build-push-docker.yml

Add step that sets the version inside the package.json before building the image.

---

Dockerfile

Update the version used in the docker-image. The version in the image should match the one used in the server's package.json.

Update Puppeteer version in the Docker image

---

client/src/components/Markdown.tsx
client/src/components/attendance-controls/components/AttendanceNotePopper.tsx

This PR fixes some issues regarding the upcoming 2.2.0 release.
- AttendanceNote dialog was closing instantly.
- Markdown component did not load markdown if no `markdown` prop but an `html` prop is provided.

Release fixes

---

client/src/components/info-paper/InfoPaper.tsx
client/src/pages/student-info/StudentInfo.tsx
client/src/pages/student-info/components/AttendanceInformation.tsx
client/src/pages/student-info/components/CriteriaCharts.tsx
client/src/pages/student-info/components/GradingTabs.tsx
client/src/pages/student-info/components/StudentDetails.tsx
docs/docs/handbook/student_info.md

Add the ilias name to the student info page.
- Closes #885

Issue 885 add saved ilias name of student to student overview

---

docs/src/css/custom.scss

Fixes an issue with the documentation's alert boxes.

Fix border style not being correctly applied to alert boxes.

---

client/src/hooks/fetching/Axios.tsx
client/src/pages/tutorialmanagement/sorters/Sorters.ts
client/src/routes/Routing.types.tsx
server/src/module/information/information.controller.ts
server/src/module/information/information.service.ts

Small fixes leading up to the `2.3.0` release.

Small fixes

---

.github/workflows/build-push-docker.yml
.github/workflows/code-quality.yml
.github/workflows/deploy-docs.yml
.github/workflows/docker-build-test.yml
.github/workflows/unit-tests.yml

Bump actions/checkout to v2 for all workflows.

---

server/src/module/pdf/subservices/PDFGenerator.schein.ts
server/src/module/pdf/subservices/PDFGenerator.withStudents.ts

This fixes an unecessary fetch of students done in the ScheinResultsPDFGenerator::generatePDF() function.

Fix unecessary fetch of students in ScheinResultsPDFGenerator.

---

server/config/development.yml
server/config/production.yml
server/src/module/pdf/subservices/PDFGenerator.core.ts
server/src/module/settings/model/ApplicationConfiguration.ts
server/src/module/settings/model/PuppeteerConfiguration.ts
server/src/module/settings/settings.service.ts
server/src/module/settings/settings.static.ts

Adds the ability to pass a timeout through the config files to puppeteer.

Add timeout option to pass to puppeteer.

---

server/src/module/student/grading.service.ts

Fixes failing pdf export (`$contains` is postgres specific)
- Fixes #1019

fix getting handins

---

server/src/database/entities/grading.entity.ts

cascading deletes for gradings
- Closes #1026

add cascading deletes

---

.github/workflows/build-push-docker.yml
.github/workflows/code-quality.yml
.github/workflows/deploy-docs.yml
.github/workflows/docker-build-test.yml
.github/workflows/unit-tests.yml
Dockerfile
docs/docs/dev/setup-env.md
package.json

currently the newest pnpm is installed which is not compatible with the node version

fix CI (hopefully)

---

client/src/pages/studentmanagement/student-list/StudentList.helpers.ts

The student lists are now correctly displayed when changing tutorials within the same view
#1014

Fix lists are not updated with new group data when switching groups within the same view

---

client/src/pages/studentmanagement/TutorStudentmanagement.tsx
client/src/pages/studentmanagement/student-list/StudentList.helpers.ts
server/src/module/scheincriteria/scheincriteria.service.ts

Fixes the display of student list for admins, display of scheinstatus after creating a student and the disappearance of the top bar after changing tutoriums with previously opened create student form. Also fixes scheinstatus not passed for students with schein from previous semesters.
#1044, #1048, #1052, #1050

Fixes to the display of stundent list, scheinstatus and top bar

---

client/src/components/forms/TutorialForm.tsx
client/src/components/forms/UserForm.tsx
client/src/components/forms/components/FormikAutocompleteSelect.tsx

Add auto-completion feature for tutor and corrector search field in the tutorial create/edit form
#43

Feature auto completion for tutor search

---

client/src/hooks/fetching/Files.ts
client/src/pages/usermanagement/UserManagement.tsx
server/src/module/excel/excel.controller.ts
server/src/module/excel/excel.module.ts
server/src/module/excel/excel.service.ts

Enables admins to download user credentials as a xlsx file
#39

Add feature user xlsx export

---

.github/workflows/build-push-docker.yml
.github/workflows/code-quality.yml
.github/workflows/deploy-docs.yml
.github/workflows/unit-tests.yml

Update the node version in github actions

Update gh actions node version

---

client/src/components/markdown/Markdown.tsx
client/src/pages/points-sheet/enter-form/EnterPoints.tsx
client/src/pages/points-sheet/enter-form/components/EnterPointsForm.tsx

Add an all exercises select option to the enter sheet points page
Fix markdown fetch
#231

Feature all exercises tab

---

client/src/pages/attendance/AttendanceManager.tsx

Workaround fix for the all present button in student attendance manager
#1034

Workaround fix all present button

---

client/src/components/import-csv/components/map-form/MapForm.tsx
client/src/pages/import-short-tests/components/adjust-generated-short-test/AdjustGeneratedShortTest.tsx
server/src/module/scheinexam/scheinexam.service.ts
server/src/module/sheet/sheet.service.ts
server/src/module/short-test/short-test.service.ts
server/src/module/student/grading.controller.ts
server/src/module/student/grading.service.ts

Get rid of multiple single student queries to the db to shorten import time
#1033

Fix performance issues of Scheinquiz import
